# Generated by Django 3.2.6 on 2021-09-12 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagementCenter', '0003_auto_20210828_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManagementCenter.departement'),
        ),
        migrations.AlterField(
            model_name='group',
            name='UserManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
